import type { TechNode } from './types'

/**
 * Military tech tree — early tiers (layout mirrors in-game branching shown in screenshot).
 * Tighter vertical spacing to fit all nodes on screen.
 */
const COL = 450
const ROW = 90
const START_X = 100

export const militaryTree: TechNode[] = [
  // ===== COLUMN 0 (root) =====
  {
    id: 'military_discipline',
    name: 'Military Discipline',
    icon: '/tech/military_discipline.png',
    level: 0,
    maxLevel: 1,
    x: START_X + 0 * COL,
    y: 3 * ROW,
    parents: [],
    requirements: {},
    timeCost: 0,
    power: 0,
    mgePoints: 0,
    resourceCosts: {},
  },

  // ===== COLUMN 1 (weapon / troop dmg / cav / archer) =====
  {
    id: 'iron_working',
    name: 'Iron Working',
    icon: '/tech/iron_working.png',
    level: 0,
    maxLevel: 5,
    x: START_X + 1 * COL,
    y: 0 * ROW,
    parents: ['military_discipline'],
    requirements: {
      military_discipline: 1,
    },
    timeCost: 0,
    power: 0,
    mgePoints: 0,
    resourceCosts: {},
  },
  {
    id: 'improved_fletching',
    name: 'Improved Fletching',
    icon: '/tech/improved_fletching.png',
    level: 0,
    maxLevel: 5,
    x: START_X + 1 * COL,
    y: 2 * ROW,
    parents: ['military_discipline'],
    requirements: {
      military_discipline: 1,
    },
    timeCost: 0,
    power: 0,
    mgePoints: 0,
    resourceCosts: {},
  },
  {
    id: 'horsemanship',
    name: 'Horsemanship',
    icon: '/tech/horsemanship.png',
    level: 0,
    maxLevel: 5,
    x: START_X + 1 * COL,
    y: 4 * ROW,
    parents: ['military_discipline'],
    requirements: {
      military_discipline: 1,
    },
    timeCost: 0,
    power: 0,
    mgePoints: 0,
    resourceCosts: {},
  },
  {
    id: 'flaming_projectile',
    name: 'Flaming Projectile',
    icon: '/tech/flaming_projectile.png',
    level: 0,
    maxLevel: 5,
    x: START_X + 1 * COL,
    y: 6 * ROW,
    parents: ['military_discipline'],
    requirements: {
      military_discipline: 1,
    },
    timeCost: 0,
    power: 0,
    mgePoints: 0,
    resourceCosts: {},
  },

  // ===== COLUMN 2 =====
  {
    id: 'swordsman',
    name: 'Swordsman',
    icon: '/tech/swordsman.png',
    level: 0,
    maxLevel: 1,
    x: START_X + 2 * COL,
    y: 0 * ROW,
    parents: ['iron_working'],
    requirements: {
      iron_working: 3,
    },
    timeCost: 0,
    power: 0,
    mgePoints: 0,
    resourceCosts: {},
  },
  {
    id: 'bowman',
    name: 'Bowman',
    icon: '/tech/bowman.png',
    level: 0,
    maxLevel: 1,
    x: START_X + 2 * COL,
    y: 2 * ROW,
    parents: ['improved_fletching'],
    requirements: {
      improved_fletching: 3,
    },
    timeCost: 0,
    power: 0,
    mgePoints: 0,
    resourceCosts: {},
  },
  {
    id: 'light_cavalry',
    name: 'Light Cavalry',
    icon: '/tech/light_cavalry.png',
    level: 0,
    maxLevel: 1,
    x: START_X + 2 * COL,
    y: 4 * ROW,
    parents: ['horsemanship'],
    requirements: {
      horsemanship: 3,
    },
    timeCost: 0,
    power: 0,
    mgePoints: 0,
    resourceCosts: {},
  },
  {
    id: 'arcuballista',
    name: 'Arcuballista',
    icon: '/tech/arcuballista.png',
    level: 0,
    maxLevel: 1,
    x: START_X + 2 * COL,
    y: 6 * ROW,
    parents: ['flaming_projectile'],
    requirements: {
      flaming_projectile: 3,
    },
    timeCost: 0,
    power: 0,
    mgePoints: 0,
    resourceCosts: {},
  },

  // ===== COLUMN 3 =====
  {
    id: 'tracking',
    name: 'Tracking',
    icon: '/tech/tracking.png',
    level: 0,
    maxLevel: 5,
    x: START_X + 3 * COL,
    y: 1 * ROW,
    parents: ['bowman', 'swordsman'],
    requirements: {
      swordsman: 1,
      bowman: 1,
    },
    timeCost: 0,
    power: 0,
    mgePoints: 0,
    resourceCosts: {},
  },
  {
    id: 'pathfinding',
    name: 'Pathfinding',
    icon: '/tech/pathfinding.png',
    level: 0,
    maxLevel: 5,
    x: START_X + 3 * COL,
    y: 5 * ROW,
    parents: ['light_cavalry', 'arcuballista'],
    requirements: {
      light_cavalry: 1,
      arcuballista: 1,
    },
    timeCost: 0,
    power: 0,
    mgePoints: 0,
    resourceCosts: {},
  },

  // ===== COLUMN 4 =====
  {
    id: 'buckler',
    name: 'Buckler',
    icon: '/tech/buckler.png',
    level: 0,
    maxLevel: 5,
    x: START_X + 4 * COL,
    y: 0 * ROW,
    parents: ['tracking'],
    requirements: {},
    timeCost: 0,
    power: 0,
    mgePoints: 0,
    resourceCosts: {},
  },
  {
    id: 'leather_armor',
    name: 'Leather Armor',
    icon: '/tech/leather_armor.png',
    level: 0,
    maxLevel: 5,
    x: START_X + 4 * COL,
    y: 2 * ROW,
    parents: ['tracking'],
    requirements: {},
    timeCost: 0,
    power: 0,
    mgePoints: 0,
    resourceCosts: {},
  },
  {
    id: 'scale_armor',
    name: 'Scale Armor',
    icon: '/tech/scale_armor.png',
    level: 0,
    maxLevel: 5,
    x: START_X + 4 * COL,
    y: 4 * ROW,
    parents: ['pathfinding'],
    requirements: {},
    timeCost: 0,
    power: 0,
    mgePoints: 0,
    resourceCosts: {},
  },
  {
    id: 'enhanced_axle',
    name: 'Enhanced Axle',
    icon: '/tech/enhanced_axle.png',
    level: 0,
    maxLevel: 4,
    x: START_X + 4 * COL,
    y: 6 * ROW,
    parents: ['pathfinding'],
    requirements: {},
    timeCost: 0,
    power: 0,
    mgePoints: 0,
    resourceCosts: {},
  },

  // ===== COLUMN 5 (unit unlocks) =====
  {
    id: 'spearman',
    name: 'Spearman',
    icon: '/tech/spearman.png',
    level: 0,
    maxLevel: 1,
    x: START_X + 5 * COL,
    y: 0 * ROW,
    parents: ['buckler'],
    requirements: {},
    timeCost: 0,
    power: 0,
    mgePoints: 0,
    resourceCosts: {},
  },
  {
    id: 'composite_bowman',
    name: 'Composite Bowman',
    icon: '/tech/composite_bowman.png',
    level: 0,
    maxLevel: 1,
    x: START_X + 5 * COL,
    y: 2 * ROW,
    parents: ['leather_armor'],
    requirements: {},
    timeCost: 0,
    power: 0,
    mgePoints: 0,
    resourceCosts: {},
  },
  {
    id: 'heavy_cavalry',
    name: 'Heavy Cavalry',
    icon: '/tech/heavy_cavalry.png',
    level: 0,
    maxLevel: 1,
    x: START_X + 5 * COL,
    y: 4 * ROW,
    parents: ['scale_armor'],
    requirements: {},
    timeCost: 0,
    power: 0,
    mgePoints: 0,
    resourceCosts: {},
  },
  {
    id: 'mangonel',
    name: 'Mangonel',
    icon: '/tech/mangonel.png',
    level: 0,
    maxLevel: 1,
    x: START_X + 5 * COL,
    y: 6 * ROW,
    parents: ['enhanced_axle'],
    requirements: {},
    timeCost: 0,
    power: 0,
    mgePoints: 0,
    resourceCosts: {},
  },

  // ===== COLUMN 6 (Camouflage - branching tech) =====
  {
    id: 'camouflage',
    name: 'Camouflage',
    icon: '/tech/camouflage.png',
    level: 0,
    maxLevel: 5,
    x: START_X + 6 * COL,
    y: 3 * ROW,
    parents: ['spearman', 'composite_bowman', 'heavy_cavalry', 'mangonel'],
    requirements: {},
    timeCost: 0,
    power: 0,
    mgePoints: 0,
    resourceCosts: {},
  },

  // ===== COLUMN 7 (middle tier techs) =====
  {
    id: 'combat_tactics',
    name: 'Combat Tactics',
    icon: '/tech/combat_tactics.png',
    level: 0,
    maxLevel: 10,
    x: START_X + 7 * COL,
    y: 1 * ROW,
    parents: ['camouflage'],
    requirements: {},
    timeCost: 0,
    power: 0,
    mgePoints: 0,
    resourceCosts: {},
  },
  {
    id: 'defensive_formation',
    name: 'Defensive Formation',
    icon: '/tech/defensive_formation.png',
    level: 0,
    maxLevel: 10,
    x: START_X + 7 * COL,
    y: 3 * ROW,
    parents: ['camouflage'],
    requirements: {},
    timeCost: 0,
    power: 0,
    mgePoints: 0,
    resourceCosts: {},
  },
  {
    id: 'herbal_medicine',
    name: 'Herbal Medicine',
    icon: '/tech/herbal_medicine.png',
    level: 0,
    maxLevel: 10,
    x: START_X + 7 * COL,
    y: 5 * ROW,
    parents: ['camouflage'],
    requirements: {},
    timeCost: 0,
    power: 0,
    mgePoints: 0,
    resourceCosts: {},
  },

  // ===== COLUMN 8 (Cartography own column) =====
  {
    id: 'cartography',
    name: 'Cartography',
    icon: '/tech/cartography.png',
    level: 0,
    maxLevel: 5,
    x: START_X + 8 * COL,
    y: 3 * ROW,
    parents: ['combat_tactics', 'defensive_formation', 'herbal_medicine'],
    requirements: {},
    timeCost: 0,
    power: 0,
    mgePoints: 0,
    resourceCosts: {},
  },

  // ===== COLUMN 9 (unit upgrades tier 2) =====
  {
    id: 'long_swordsman',
    name: 'Long Swordsman',
    icon: '/tech/long_swordsman.png',
    level: 0,
    maxLevel: 1,
    x: START_X + 9 * COL,
    y: 0 * ROW,
    parents: ['cartography'],
    requirements: {},
    timeCost: 0,
    power: 0,
    mgePoints: 0,
    resourceCosts: {},
  },
  {
    id: 'crossbowman',
    name: 'Crossbowman',
    icon: '/tech/crossbowman.png',
    level: 0,
    maxLevel: 1,
    x: START_X + 9 * COL,
    y: 2 * ROW,
    parents: ['cartography'],
    requirements: {},
    timeCost: 0,
    power: 0,
    mgePoints: 0,
    resourceCosts: {},
  },
  {
    id: 'teutonic_knight',
    name: 'Teutonic Knight',
    icon: '/tech/teutonic_knight.png',
    level: 0,
    maxLevel: 1,
    x: START_X + 9 * COL,
    y: 4 * ROW,
    parents: ['cartography'],
    requirements: {},
    timeCost: 0,
    power: 0,
    mgePoints: 0,
    resourceCosts: {},
  },
  {
    id: 'ballista',
    name: 'Ballista',
    icon: '/tech/ballista.png',
    level: 0,
    maxLevel: 1,
    x: START_X + 9 * COL,
    y: 6 * ROW,
    parents: ['cartography'],
    requirements: {},
    timeCost: 0,
    power: 0,
    mgePoints: 0,
    resourceCosts: {},
  },

  // ===== COLUMN 10 (upgrade techs) =====
  {
    id: 'wootz_steel',
    name: 'Wootz Steel',
    icon: '/tech/wootz_steel.png',
    level: 0,
    maxLevel: 5,
    x: START_X + 10 * COL,
    y: 0 * ROW,
    parents: ['long_swordsman'],
    requirements: {},
    timeCost: 0,
    power: 0,
    mgePoints: 0,
    resourceCosts: {},
  },
  {
    id: 'bodkin_arrows',
    name: 'Bodkin Arrows',
    icon: '/tech/bodkin_arrows.png',
    level: 0,
    maxLevel: 3,
    x: START_X + 10 * COL,
    y: 2 * ROW,
    parents: ['crossbowman'],
    requirements: {},
    timeCost: 0,
    power: 0,
    mgePoints: 0,
    resourceCosts: {},
  },
  {
    id: 'stirrups',
    name: 'Stirrups',
    icon: '/tech/stirrups.png',
    level: 0,
    maxLevel: 9,
    x: START_X + 10 * COL,
    y: 4 * ROW,
    parents: ['teutonic_knight'],
    requirements: {},
    timeCost: 0,
    power: 0,
    mgePoints: 0,
    resourceCosts: {},
  },
  {
    id: 'ballistics',
    name: 'Ballistics',
    icon: '/tech/ballistics.png',
    level: 0,
    maxLevel: 1,
    x: START_X + 10 * COL,
    y: 6 * ROW,
    parents: ['ballista'],
    requirements: {},
    timeCost: 0,
    power: 0,
    mgePoints: 0,
    resourceCosts: {},
  },

  // ===== COLUMN 11 (advanced armor/frame) =====
  {
    id: 'scutum',
    name: 'Scutum',
    icon: '/tech/scutum.png',
    level: 0,
    maxLevel: 6,
    x: START_X + 11 * COL,
    y: 0 * ROW,
    parents: ['wootz_steel'],
    requirements: {},
    timeCost: 0,
    power: 0,
    mgePoints: 0,
    resourceCosts: {},
  },
  {
    id: 'pavise',
    name: 'Pavise',
    icon: '/tech/pavise.png',
    level: 0,
    maxLevel: 3,
    x: START_X + 11 * COL,
    y: 2 * ROW,
    parents: ['bodkin_arrows'],
    requirements: {},
    timeCost: 0,
    power: 0,
    mgePoints: 0,
    resourceCosts: {},
  },
  {
    id: 'plate_armor',
    name: 'Plate Armor',
    icon: '/tech/plate_armor.png',
    level: 0,
    maxLevel: 9,
    x: START_X + 11 * COL,
    y: 4 * ROW,
    parents: ['stirrups'],
    requirements: {},
    timeCost: 0,
    power: 0,
    mgePoints: 0,
    resourceCosts: {},
  },
  {
    id: 'heavy_frame',
    name: 'Heavy Frame',
    icon: '/tech/heavy_frame.png',
    level: 0,
    maxLevel: 1,
    x: START_X + 11 * COL,
    y: 6 * ROW,
    parents: ['ballistics'],
    requirements: {},
    timeCost: 0,
    power: 0,
    mgePoints: 0,
    resourceCosts: {},
  },

  // ===== COLUMN 12 (Medical Corps own column) =====
  {
    id: 'medical_corps',
    name: 'Medical Corps',
    icon: '/tech/medical_corps.png',
    level: 0,
    maxLevel: 8,
    x: START_X + 12 * COL,
    y: 3 * ROW,
    parents: ['scutum', 'pavise', 'plate_armor', 'heavy_frame'],
    requirements: {},
    timeCost: 0,
    power: 0,
    mgePoints: 0,
    resourceCosts: {},
  },

  // ===== COLUMN 13 (support/elite connection) =====
  {
    id: 'combined_arms',
    name: 'Combined Arms',
    icon: '/tech/combined_arms.png',
    level: 0,
    maxLevel: 9,
    x: START_X + 13 * COL,
    y: 1 * ROW,
    parents: ['medical_corps'],
    requirements: {},
    timeCost: 0,
    power: 0,
    mgePoints: 0,
    resourceCosts: {},
  },
  {
    id: 'encampment',
    name: 'Encampment',
    icon: '/tech/encampment.png',
    level: 0,
    maxLevel: 7,
    x: START_X + 13 * COL,
    y: 5 * ROW,
    parents: ['medical_corps'],
    requirements: {},
    timeCost: 0,
    power: 0,
    mgePoints: 0,
    resourceCosts: {},
  },

  // ===== COLUMN 14 (elite units) =====
  {
    id: 'royal_guard',
    name: 'Royal Guard',
    icon: '/tech/royal_guard.png',
    level: 0,
    maxLevel: 1,
    x: START_X + 14.5 * COL,
    y: 0 * ROW,
    parents: ['medical_corps'],
    requirements: {},
    timeCost: 0,
    power: 0,
    mgePoints: 0,
    resourceCosts: {},
  },
  {
    id: 'royal_crossbowman',
    name: 'Royal Crossbowman',
    icon: '/tech/royal_crossbowman.png',
    level: 0,
    maxLevel: 1,
    x: START_X + 14.5 * COL,
    y: 2 * ROW,
    parents: ['medical_corps'],
    requirements: {},
    timeCost: 0,
    power: 0,
    mgePoints: 0,
    resourceCosts: {},
  },
  {
    id: 'elite_teutonic_knight',
    name: 'Elite Teutonic Knight',
    icon: '/tech/elite_teutonic_knight.png',
    level: 0,
    maxLevel: 1,
    x: START_X + 14.5 * COL,
    y: 4 * ROW,
    parents: ['medical_corps'],
    requirements: {},
    timeCost: 0,
    power: 0,
    mgePoints: 0,
    resourceCosts: {},
  },
  {
    id: 'trebuchet',
    name: 'Trebuchet',
    icon: '/tech/trebuchet.png',
    level: 0,
    maxLevel: 1,
    x: START_X + 14.5 * COL,
    y: 6 * ROW,
    parents: ['medical_corps'],
    requirements: {},
    timeCost: 0,
    power: 0,
    mgePoints: 0,
    resourceCosts: {},
  },
]
