import type { ForgeItem } from './equipment-forge-data'

export const EQUIPMENT_FORGE_SEED_ITEMS: ForgeItem[] = [
  {
    id: "dragons_breath_bow",
    name: "Dragon's Breath Bow",
    slot: "weapon",
    rarity: "legendary",
    equipmentLevel: 50,
    iconUrl: "/images/equipment/dragons_breath_bow.webp",
    canForge: true,
    attributes: [
      { label: "Cavalry Health", value: "+5%", color: "orange" },
      { label: "Infantry Health", value: "+5%", color: "red" },
      { label: "Archer Defense", value: "+20%", color: "pink" },
    ],
    materials: [
      { materialId: "leather", amount: 15 },
      { materialId: "iron", amount: 15 },
      { materialId: "ebony", amount: 60 },
    ],
    goldCost: 20000000,
  },
  {
    id: "hammer_of_the_sun_and_moon",
    name: "Hammer of the Sun and Moon",
    slot: "weapon",
    rarity: "legendary",
    equipmentLevel: 50,
    iconUrl: "/images/equipment/hammer_of_the_sun_and_moon.webp",
    canForge: true,
    attributes: [
      { label: "Infantry Attack", value: "+25%", color: "red" },
      { label: "Archer Health", value: "+5%", color: "pink" },
    ],
    materials: [
      { materialId: "leather", amount: 10 },
      { materialId: "iron", amount: 70 },
      { materialId: "ebony", amount: 10 },
    ],
    goldCost: 30000000,
  },
  {
    id: "lance_of_the_hellish_wasteland",
    name: "Lance of the Hellish Wasteland",
    slot: "weapon",
    rarity: "legendary",
    equipmentLevel: 50,
    iconUrl: "/images/equipment/lance_of_the_hellish_wasteland.webp",
    canForge: true,
    attributes: [
      { label: "Cavalry Attack", value: "+20%", color: "orange" },
      { label: "Infantry Health", value: "+5%", color: "red" },
      { label: "Archer Attack", value: "+5%", color: "pink" },
    ],
    materials: [
      { materialId: "leather", amount: 60 },
      { materialId: "iron", amount: 15 },
      { materialId: "ebony", amount: 15 },
    ],
    goldCost: 20000000,
  },
  {
    id: "sacred_dominion",
    name: "Sacred Dominion",
    slot: "weapon",
    rarity: "legendary",
    equipmentLevel: 50,
    iconUrl: "/images/equipment/sacred_dominion.webp",
    canForge: true,
    attributes: [
      { label: "Cavalry Attack", value: "+25%", color: "orange" },
      { label: "Archer Defense", value: "+5%", color: "pink" },
    ],
    materials: [
      { materialId: "leather", amount: 70 },
      { materialId: "iron", amount: 10 },
      { materialId: "ebony", amount: 10 },
    ],
    goldCost: 30000000,
  },
  {
    id: "shield_of_the_eternal_empire",
    name: "Shield of the Eternal Empire",
    slot: "weapon",
    rarity: "legendary",
    equipmentLevel: 50,
    iconUrl: "/images/equipment/shield_of_the_eternal_empire.webp",
    canForge: true,
    attributes: [
      { label: "Cavalry Attack", value: "+5%", color: "orange" },
      { label: "Infantry Attack", value: "+20%", color: "red" },
      { label: "Archer Attack", value: "+5%", color: "pink" },
    ],
    materials: [
      { materialId: "leather", amount: 15 },
      { materialId: "iron", amount: 60 },
      { materialId: "ebony", amount: 15 },
    ],
    goldCost: 20000000,
  },
  {
    id: "the_hydras_blast",
    name: "The Hydra's Blast",
    slot: "weapon",
    rarity: "legendary",
    equipmentLevel: 50,
    iconUrl: "/images/equipment/the_hydras_blast.webp",
    canForge: true,
    attributes: [
      { label: "Cavalry Defense", value: "+5%", color: "orange" },
      { label: "Archer Defense", value: "+25%", color: "pink" },
    ],
    materials: [
      { materialId: "leather", amount: 10 },
      { materialId: "iron", amount: 10 },
      { materialId: "ebony", amount: 70 },
    ],
    goldCost: 30000000,
  },
  {
    id: "trial_of_the_lost_kingdom",
    name: "Trial of the Lost Kingdom",
    slot: "weapon",
    rarity: "legendary",
    equipmentLevel: 50,
    iconUrl: "/images/equipment/trial_of_the_lost_kingdom.webp",
    canForge: true,
    attributes: [
      { label: "Cavalry Defense", value: "+15%", color: "orange" },
      { label: "Infantry Health", value: "+5%", color: "red" },
      { label: "Archer Attack", value: "+5%", color: "pink" },
    ],
    materials: [],
    goldCost: 0,
  },
  {
    id: "twilight_epiphany",
    name: "Twilight Epiphany",
    slot: "weapon",
    rarity: "legendary",
    equipmentLevel: 50,
    iconUrl: "/images/equipment/twilight_epiphany.webp",
    canForge: true,
    attributes: [
      { label: "Siege Attack", value: "+25%", color: "purple" },
      { label: "Siege March Speed", value: "+6%", color: "purple" },
    ],
    materials: [
      { materialId: "leather", amount: 30 },
      { materialId: "iron", amount: 30 },
      { materialId: "ebony", amount: 30 },
    ],
    goldCost: 30000000,
  },
  {
    id: "scepter_of_the_glorious_goddess",
    name: "Scepter of the Glorious Goddess",
    slot: "weapon",
    rarity: "legendary",
    equipmentLevel: 50,
    iconUrl: "/images/equipment/scepter_of_the_glorious_goddess.webp",
    canForge: true,
    attributes: [
      { label: "Infantry March Speed", value: "+3%", color: "red" },
      { label: "Troop Attack", value: "+15%", color: "green" },
    ],
    materials: [
      { materialId: "leather", amount: 30 },
      { materialId: "iron", amount: 30 },
      { materialId: "ebony", amount: 30 },
    ],
    goldCost: 20000000,
  },
  {
    id: "witchs_feathered_staff",
    name: "Witch's Feathered Staff",
    slot: "weapon",
    rarity: "legendary",
    equipmentLevel: 50,
    iconUrl: "/images/equipment/witchs_feathered_staff.webp",
    canForge: true,
    attributes: [
      { label: "Siege Defense", value: "+6%", color: "purple" },
      { label: "Siege March Speed", value: "+3%", color: "purple" },
    ],
    specialTalent: "Gathering Speed 15%",
    materials: [
      { materialId: "bone", amount: 35 },
    ],
    goldCost: 20000000,
  },
  {
    id: "heart_of_the_saint",
    name: "Heart of the Saint",
    slot: "weapon",
    rarity: "epic",
    equipmentLevel: 40,
    iconUrl: "/images/equipment/heart_of_the_saint.webp",
    canForge: true,
    attributes: [
      { label: "Cavalry Defense", value: "+13%", color: "orange" },
      { label: "Infantry Health", value: "+4%", color: "red" },
      { label: "Archer Health", value: "+6%", color: "pink" },
    ],
    materials: [
      { materialId: "leather", amount: 70 },
      { materialId: "iron", amount: 15 },
      { materialId: "ebony", amount: 15 },
    ],
    goldCost: 5000000,
  },
  {
    id: "golden_age",
    name: "Golden Age",
    slot: "weapon",
    rarity: "epic",
    equipmentLevel: 40,
    iconUrl: "/images/equipment/golden_age.webp",
    canForge: true,
    attributes: [
      { label: "Cavalry Attack", value: "+4%", color: "orange" },
      { label: "Infantry Defense", value: "+6%", color: "red" },
      { label: "Archer Defense", value: "+13%", color: "pink" },
    ],
    materials: [
      { materialId: "leather", amount: 15 },
      { materialId: "iron", amount: 15 },
      { materialId: "ebony", amount: 70 },
    ],
    goldCost: 5000000,
  },
  {
    id: "sakura_fubuki",
    name: "Sakura Fubuki",
    slot: "weapon",
    rarity: "epic",
    equipmentLevel: 40,
    iconUrl: "/images/equipment/sakura_fubuki.webp",
    canForge: true,
    attributes: [
      { label: "Cavalry Health", value: "+6%", color: "orange" },
      { label: "Infantry Attack", value: "+13%", color: "red" },
      { label: "Archer Attack", value: "+4%", color: "pink" },
    ],
    materials: [
      { materialId: "leather", amount: 15 },
      { materialId: "iron", amount: 70 },
      { materialId: "ebony", amount: 15 },
    ],
    goldCost: 5000000,
  },
  {
    id: "scepter_of_the_forest_guardian",
    name: "Scepter of the Forest Guardian",
    slot: "weapon",
    rarity: "epic",
    equipmentLevel: 40,
    iconUrl: "/images/equipment/scepter_of_the_forest_guardian.webp",
    canForge: true,
    attributes: [
      { label: "Cavalry Attack", value: "+6%", color: "orange" },
      { label: "Siege Defense", value: "+6%", color: "purple" },
    ],
    specialTalent: "Gathering Speed 10%",
    materials: [
      { materialId: "bone", amount: 35 },
    ],
    goldCost: 6000000,
  },
  {
    id: "knights_oathsworn_bow",
    name: "Knight's Oathsworn Bow",
    slot: "weapon",
    rarity: "epic",
    equipmentLevel: 40,
    iconUrl: "/images/equipment/knights_oathsworn_bow.webp",
    canForge: true,
    attributes: [
      { label: "Siege Attack", value: "+13%", color: "purple" },
      { label: "Siege March Speed", value: "+2%", color: "purple" },
    ],
    materials: [
      { materialId: "leather", amount: 30 },
      { materialId: "iron", amount: 30 },
      { materialId: "ebony", amount: 30 },
    ],
    goldCost: 5000000,
  },
  {
    id: "blazing_axe",
    name: "Blazing Axe",
    slot: "weapon",
    rarity: "rare",
    equipmentLevel: 30,
    iconUrl: "/images/equipment/blazing_axe.webp",
    canForge: false,
    attributes: [
      { label: "Cavalry Attack", value: "+8%", color: "orange" },
      { label: "Infantry Attack", value: "+3%", color: "red" },
      { label: "Archer Attack", value: "+5%", color: "pink" },
    ],
    materials: [
      { materialId: "leather", amount: 50 },
      { materialId: "iron", amount: 20 },
      { materialId: "ebony", amount: 20 },
    ],
    goldCost: 2000000,
  },
  {
    id: "gatekeepers_shield",
    name: "Gatekeeper's Shield",
    slot: "weapon",
    rarity: "rare",
    equipmentLevel: 30,
    iconUrl: "/images/equipment/gatekeepers_shield.webp",
    canForge: false,
    attributes: [
      { label: "Cavalry Health", value: "+5%", color: "orange" },
      { label: "Infantry Health", value: "+8%", color: "red" },
    ],
    specialTalent: "Commander EXP Gain 3%",
    materials: [
      { materialId: "leather", amount: 20 },
      { materialId: "iron", amount: 50 },
      { materialId: "ebony", amount: 20 },
    ],
    goldCost: 2000000,
  },
  {
    id: "staff_of_the_lost",
    name: "Staff of the Lost",
    slot: "weapon",
    rarity: "rare",
    equipmentLevel: 30,
    iconUrl: "/images/equipment/staff_of_the_lost.webp",
    canForge: false,
    attributes: [
      { label: "Cavalry Defense", value: "+3%", color: "orange" },
      { label: "Infantry Defense", value: "+5%", color: "red" },
      { label: "Archer Defense", value: "+8%", color: "pink" },
    ],
    materials: [
      { materialId: "leather", amount: 20 },
      { materialId: "iron", amount: 20 },
      { materialId: "ebony", amount: 50 },
    ],
    goldCost: 2000000,
  },
  {
    id: "blessed_blade",
    name: "Blessed Blade",
    slot: "weapon",
    rarity: "uncommon",
    equipmentLevel: 20,
    iconUrl: "/images/equipment/blessed_blade.webp",
    canForge: false,
    attributes: [
      { label: "Infantry Health", value: "+6%", color: "red" },
      { label: "Archer Attack", value: "+4%", color: "pink" },
    ],
    specialTalent: "Damage to Barbarians 3%",
    materials: [
      { materialId: "iron", amount: 60 },
      { materialId: "ebony", amount: 20 },
    ],
    goldCost: 500000,
  },
  {
    id: "vanguard_halberd",
    name: "Vanguard Halberd",
    slot: "weapon",
    rarity: "uncommon",
    equipmentLevel: 20,
    iconUrl: "/images/equipment/vanguard_halberd.webp",
    canForge: false,
    attributes: [
      { label: "Cavalry Defense", value: "+5%", color: "orange" },
      { label: "Cavalry Health", value: "+4%", color: "orange" },
    ],
    materials: [
      { materialId: "leather", amount: 110 },
    ],
    goldCost: 750000,
  },
  {
    id: "sharp_longsword",
    name: "Sharp Longsword",
    slot: "weapon",
    rarity: "common",
    equipmentLevel: 10,
    iconUrl: "/images/equipment/sharp_longsword.webp",
    canForge: false,
    attributes: [
      { label: "Cavalry Defense", value: "+5%", color: "orange" },
    ],
    specialTalent: "Gathering Speed 2%",
    materials: [
      { materialId: "leather", amount: 100 },
    ],
    goldCost: 100000,
  },
  {
    id: "gold_helm_of_the_eternal_empire",
    name: "Gold Helm of the Eternal Empire",
    slot: "helmet",
    rarity: "legendary",
    equipmentLevel: 50,
    iconUrl: "/images/equipment/gold_helm_of_the_eternal_empire.webp",
    canForge: true,
    attributes: [
      { label: "Cavalry Health", value: "+3%", color: "orange" },
      { label: "Infantry Defense", value: "+11%", color: "red" },
      { label: "Archer Health", value: "+4%", color: "pink" },
    ],
    materials: [
      { materialId: "leather", amount: 10 },
      { materialId: "iron", amount: 40 },
      { materialId: "ebony", amount: 10 },
    ],
    goldCost: 20000000,
  },
  {
    id: "dragons_breath_helm",
    name: "Dragon's Breath Helm",
    slot: "helmet",
    rarity: "legendary",
    equipmentLevel: 50,
    iconUrl: "/images/equipment/dragons_breath_helm.webp",
    canForge: true,
    attributes: [
      { label: "Cavalry Attack", value: "+3%", color: "orange" },
      { label: "Infantry Defense", value: "+4%", color: "red" },
      { label: "Archer Attack", value: "+11%", color: "pink" },
    ],
    materials: [
      { materialId: "leather", amount: 10 },
      { materialId: "iron", amount: 10 },
      { materialId: "ebony", amount: 40 },
    ],
    goldCost: 20000000,
  },
  {
    id: "war_helm_of_the_hellish_wasteland",
    name: "War Helm of the Hellish Wasteland",
    slot: "helmet",
    rarity: "legendary",
    equipmentLevel: 50,
    iconUrl: "/images/equipment/war_helm_of_the_hellish_wasteland.webp",
    canForge: true,
    attributes: [
      { label: "Cavalry Defense", value: "+11%", color: "orange" },
      { label: "Infantry Attack", value: "+4%", color: "red" },
      { label: "Archer Defense", value: "+3%", color: "pink" },
    ],
    materials: [
      { materialId: "leather", amount: 40 },
      { materialId: "iron", amount: 10 },
      { materialId: "ebony", amount: 10 },
    ],
    goldCost: 20000000,
  },
  {
    id: "pride_of_the_khan",
    name: "Pride of the Khan",
    slot: "helmet",
    rarity: "legendary",
    equipmentLevel: 50,
    iconUrl: "/images/equipment/pride_of_the_khan.webp",
    canForge: true,
    attributes: [
      { label: "Cavalry Defense", value: "+15%", color: "orange" },
      { label: "Archer Health", value: "+8%", color: "pink" },
    ],
    materials: [
      { materialId: "leather", amount: 50 },
      { materialId: "ebony", amount: 10 },
    ],
    goldCost: 30000000,
  },
  {
    id: "helm_of_the_conqueror",
    name: "Helm of the Conqueror",
    slot: "helmet",
    rarity: "legendary",
    equipmentLevel: 50,
    iconUrl: "/images/equipment/helm_of_the_conqueror.webp",
    canForge: true,
    attributes: [
      { label: "Cavalry Health", value: "+8%", color: "orange" },
      { label: "Infantry Defense", value: "+15%", color: "red" },
    ],
    materials: [
      { materialId: "leather", amount: 10 },
      { materialId: "iron", amount: 50 },
    ],
    goldCost: 30000000,
  },
  {
    id: "ancestral_mask_of_night",
    name: "Ancestral Mask of Night",
    slot: "helmet",
    rarity: "legendary",
    equipmentLevel: 50,
    iconUrl: "/images/equipment/ancestral_mask_of_night.webp",
    canForge: true,
    attributes: [
      { label: "Infantry Attack", value: "+8%", color: "red" },
      { label: "Archer Attack", value: "+15%", color: "pink" },
    ],
    materials: [
      { materialId: "iron", amount: 10 },
      { materialId: "ebony", amount: 50 },
    ],
    goldCost: 30000000,
  },
  {
    id: "fierce_wolfs_helmet",
    name: "Fierce Wolf's Helmet",
    slot: "helmet",
    rarity: "legendary",
    equipmentLevel: 50,
    iconUrl: "/images/equipment/fierce_wolfs_helmet.webp",
    canForge: true,
    attributes: [
      { label: "Siege Attack", value: "+14.5%", color: "purple" },
      { label: "Siege March Speed", value: "+4%", color: "purple" },
    ],
    materials: [
      { materialId: "leather", amount: 20 },
      { materialId: "iron", amount: 20 },
      { materialId: "ebony", amount: 20 },
    ],
    goldCost: 30000000,
  },
  {
    id: "diadem_of_the_glorious_goddess",
    name: "Diadem of the Glorious Goddess",
    slot: "helmet",
    rarity: "legendary",
    equipmentLevel: 50,
    iconUrl: "/images/equipment/diadem_of_the_glorious_goddess.webp",
    canForge: true,
    attributes: [
      { label: "Cavalry March Speed", value: "+2%", color: "orange" },
      { label: "Troop Attack", value: "+8%", color: "green" },
    ],
    materials: [
      { materialId: "leather", amount: 20 },
      { materialId: "iron", amount: 20 },
      { materialId: "ebony", amount: 20 },
    ],
    goldCost: 20000000,
  },
  {
    id: "witchs_deadwood_crown",
    name: "Witch's Deadwood Crown",
    slot: "helmet",
    rarity: "legendary",
    equipmentLevel: 50,
    iconUrl: "/images/equipment/witchs_deadwood_crown.webp",
    canForge: true,
    attributes: [
      { label: "Siege Attack", value: "+4%", color: "purple" },
      { label: "Siege March Speed", value: "+2%", color: "purple" },
    ],
    specialTalent: "Gathering Speed 12%",
    materials: [
      { materialId: "bone", amount: 25 },
    ],
    goldCost: 20000000,
  },
  {
    id: "revival_helm",
    name: "Revival Helm",
    slot: "helmet",
    rarity: "epic",
    equipmentLevel: 40,
    iconUrl: "/images/equipment/revival_helm.webp",
    canForge: true,
    attributes: [
      { label: "Infantry Defense", value: "+5%", color: "red" },
      { label: "Archer Defense", value: "+7.5%", color: "pink" },
    ],
    materials: [
      { materialId: "iron", amount: 10 },
      { materialId: "ebony", amount: 30 },
    ],
    goldCost: 6000000,
  },
  {
    id: "witchs_lineage",
    name: "Witch's Lineage",
    slot: "helmet",
    rarity: "epic",
    equipmentLevel: 40,
    iconUrl: "/images/equipment/witchs_lineage.webp",
    canForge: true,
    attributes: [
      { label: "Cavalry Attack", value: "+3%", color: "orange" },
      { label: "Infantry Attack", value: "+8%", color: "red" },
      { label: "Archer Defense", value: "+3%", color: "pink" },
    ],
    materials: [
      { materialId: "leather", amount: 10 },
      { materialId: "iron", amount: 30 },
      { materialId: "ebony", amount: 10 },
    ],
    goldCost: 5000000,
  },
  {
    id: "abyssal_visage",
    name: "Abyssal Visage",
    slot: "helmet",
    rarity: "epic",
    equipmentLevel: 40,
    iconUrl: "/images/equipment/abyssal_visage.webp",
    canForge: true,
    attributes: [
      { label: "Cavalry Attack", value: "+8%", color: "orange" },
      { label: "Infantry Attack", value: "+3%", color: "red" },
      { label: "Archer Attack", value: "+3%", color: "pink" },
    ],
    materials: [
      { materialId: "leather", amount: 30 },
      { materialId: "iron", amount: 10 },
      { materialId: "ebony", amount: 10 },
    ],
    goldCost: 5000000,
  },
  {
    id: "mask_of_the_forest_guardian",
    name: "Mask of the Forest Guardian",
    slot: "helmet",
    rarity: "epic",
    equipmentLevel: 40,
    iconUrl: "/images/equipment/mask_of_the_forest_guardian.webp",
    canForge: true,
    attributes: [
      { label: "Infantry Attack", value: "+4%", color: "red" },
      { label: "Siege Attack", value: "+4%", color: "purple" },
    ],
    specialTalent: "Gathering Speed 8%",
    materials: [
      { materialId: "bone", amount: 25 },
    ],
    goldCost: 6000000,
  },
  {
    id: "knights_steel_diadem",
    name: "Knight's Steel Diadem",
    slot: "helmet",
    rarity: "epic",
    equipmentLevel: 40,
    iconUrl: "/images/equipment/knights_steel_diadem.webp",
    canForge: true,
    attributes: [
      { label: "Siege Health", value: "+8%", color: "purple" },
      { label: "Siege March Speed", value: "+2%", color: "purple" },
    ],
    materials: [
      { materialId: "leather", amount: 20 },
      { materialId: "iron", amount: 20 },
      { materialId: "ebony", amount: 20 },
    ],
    goldCost: 5000000,
  },
  {
    id: "harvesters_headscarf",
    name: "Harvester's Headscarf",
    slot: "helmet",
    rarity: "rare",
    equipmentLevel: 30,
    iconUrl: "/images/equipment/harvesters_headscarf.webp",
    canForge: false,
    attributes: [
      { label: "Siege Attack", value: "+3%", color: "purple" },
      { label: "Siege Defense", value: "+3%", color: "purple" },
    ],
    specialTalent: "Gathering Speed 5%",
    materials: [
      { materialId: "bone", amount: 30 },
    ],
    goldCost: 3000000,
  },
  {
    id: "expedition_war_helm",
    name: "Expedition War Helm",
    slot: "helmet",
    rarity: "rare",
    equipmentLevel: 30,
    iconUrl: "/images/equipment/expedition_war_helm.webp",
    canForge: false,
    attributes: [
      { label: "Cavalry Defense", value: "+6%", color: "orange" },
      { label: "Infantry Defense", value: "+2%", color: "red" },
    ],
    specialTalent: "Commander EXP Gain 3%",
    materials: [
      { materialId: "leather", amount: 40 },
      { materialId: "iron", amount: 20 },
    ],
    goldCost: 2000000,
  },
  {
    id: "windswept_war_helm",
    name: "Windswept War Helm",
    slot: "helmet",
    rarity: "rare",
    equipmentLevel: 30,
    iconUrl: "/images/equipment/windswept_war_helm.webp",
    canForge: false,
    attributes: [
      { label: "Cavalry Attack", value: "+4.5%", color: "orange" },
      { label: "Infantry Attack", value: "+4.5%", color: "red" },
      { label: "Troop March Speed", value: "+3%", color: "green" },
    ],
    materials: [
      { materialId: "leather", amount: 30 },
      { materialId: "iron", amount: 30 },
    ],
    goldCost: 3000000,
  },
  {
    id: "helm_of_fear",
    name: "Helm of Fear",
    slot: "helmet",
    rarity: "uncommon",
    equipmentLevel: 20,
    iconUrl: "/images/equipment/helm_of_fear.webp",
    canForge: false,
    attributes: [
      { label: "Cavalry Attack", value: "+4%", color: "orange" },
      { label: "Infantry Defense", value: "+2%", color: "red" },
    ],
    specialTalent: "Damage to Barbarians 3%",
    materials: [
      { materialId: "leather", amount: 40 },
      { materialId: "iron", amount: 10 },
    ],
    goldCost: 500000,
  },
  {
    id: "helm_of_the_phoenix",
    name: "Helm of the Phoenix",
    slot: "helmet",
    rarity: "uncommon",
    equipmentLevel: 20,
    iconUrl: "/images/equipment/helm_of_the_phoenix.webp",
    canForge: false,
    attributes: [
      { label: "Infantry Health", value: "+2%", color: "red" },
      { label: "Archer Defense", value: "+4%", color: "pink" },
    ],
    specialTalent: "Damage to Barbarians 3%",
    materials: [
      { materialId: "iron", amount: 10 },
      { materialId: "ebony", amount: 40 },
    ],
    goldCost: 500000,
  },
  {
    id: "iron_helm",
    name: "Iron Helm",
    slot: "helmet",
    rarity: "common",
    equipmentLevel: 10,
    iconUrl: "/images/equipment/iron_helm.webp",
    canForge: false,
    attributes: [
      { label: "Infantry Attack", value: "+3%", color: "red" },
    ],
    materials: [
      { materialId: "iron", amount: 80 },
    ],
    goldCost: 100000,
  },
  {
    id: "shadow_legions_retribution",
    name: "Shadow Legion's Retribution",
    slot: "chest",
    rarity: "legendary",
    equipmentLevel: 50,
    iconUrl: "/images/equipment/shadow_legions_retribution.webp",
    canForge: true,
    attributes: [
      { label: "Cavalry Attack", value: "+12%", color: "orange" },
      { label: "Infantry Attack", value: "+5%", color: "red" },
      { label: "Archer Attack", value: "+5%", color: "pink" },
    ],
    materials: [
      { materialId: "leather", amount: 40 },
      { materialId: "iron", amount: 10 },
      { materialId: "ebony", amount: 10 },
    ],
    goldCost: 15000000,
  },
  {
    id: "the_milky_way",
    name: "The Milky Way",
    slot: "chest",
    rarity: "legendary",
    equipmentLevel: 50,
    iconUrl: "/images/equipment/the_milky_way.webp",
    canForge: true,
    attributes: [
      { label: "Cavalry Health", value: "+6%", color: "orange" },
      { label: "Archer Health", value: "+12%", color: "pink" },
    ],
    specialTalent: "Commander EXP Gain 5%",
    materials: [
      { materialId: "leather", amount: 10 },
      { materialId: "iron", amount: 10 },
      { materialId: "ebony", amount: 40 },
    ],
    goldCost: 15000000,
  },
  {
    id: "plate_of_the_eternal_empire",
    name: "Plate of the Eternal Empire",
    slot: "chest",
    rarity: "legendary",
    equipmentLevel: 50,
    iconUrl: "/images/equipment/plate_of_the_eternal_empire.webp",
    canForge: true,
    attributes: [
      { label: "Infantry Attack", value: "+11%", color: "red" },
      { label: "Archer Defense", value: "+5%", color: "pink" },
    ],
    materials: [
      { materialId: "leather", amount: 10 },
      { materialId: "iron", amount: 40 },
      { materialId: "ebony", amount: 10 },
    ],
    goldCost: 20000000,
  },
  {
    id: "hope_cloak",
    name: "Hope Cloak",
    slot: "chest",
    rarity: "legendary",
    equipmentLevel: 50,
    iconUrl: "/images/equipment/hope_cloak.webp",
    canForge: true,
    attributes: [
      { label: "Cavalry Defense", value: "+5%", color: "orange" },
      { label: "Infantry Defense", value: "+12%", color: "red" },
      { label: "Archer Defense", value: "+5%", color: "pink" },
    ],
    materials: [
      { materialId: "leather", amount: 10 },
      { materialId: "iron", amount: 40 },
      { materialId: "ebony", amount: 10 },
    ],
    goldCost: 15000000,
  },
  {
    id: "heavy_armor_of_the_hellish_wasteland",
    name: "Heavy Armor of the Hellish Wasteland",
    slot: "chest",
    rarity: "legendary",
    equipmentLevel: 50,
    iconUrl: "/images/equipment/heavy_armor_of_the_hellish_wasteland.webp",
    canForge: true,
    attributes: [
      { label: "Cavalry Health", value: "+11%", color: "orange" },
      { label: "Infantry Attack", value: "+5%", color: "red" },
    ],
    materials: [
      { materialId: "leather", amount: 40 },
      { materialId: "iron", amount: 10 },
      { materialId: "ebony", amount: 10 },
    ],
    goldCost: 20000000,
  },
  {
    id: "dragons_breath_plate",
    name: "Dragon's Breath Plate",
    slot: "chest",
    rarity: "legendary",
    equipmentLevel: 50,
    iconUrl: "/images/equipment/dragons_breath_plate.webp",
    canForge: true,
    attributes: [
      { label: "Cavalry Defense", value: "+5%", color: "orange" },
      { label: "Archer Health", value: "+11%", color: "pink" },
    ],
    materials: [
      { materialId: "leather", amount: 10 },
      { materialId: "iron", amount: 10 },
      { materialId: "ebony", amount: 40 },
    ],
    goldCost: 20000000,
  },
  {
    id: "vigilant_wolfs_leather_armor",
    name: "Vigilant Wolf's Leather Armor",
    slot: "chest",
    rarity: "legendary",
    equipmentLevel: 50,
    iconUrl: "/images/equipment/vigilant_wolfs_leather_armor.webp",
    canForge: true,
    attributes: [
      { label: "Siege Attack", value: "+14.5%", color: "purple" },
      { label: "Siege March Speed", value: "+4%", color: "purple" },
    ],
    materials: [
      { materialId: "leather", amount: 20 },
      { materialId: "iron", amount: 20 },
      { materialId: "ebony", amount: 20 },
    ],
    goldCost: 30000000,
  },
  {
    id: "plate_of_the_glorious_goddess",
    name: "Plate of the Glorious Goddess",
    slot: "chest",
    rarity: "legendary",
    equipmentLevel: 50,
    iconUrl: "/images/equipment/plate_of_the_glorious_goddess.webp",
    canForge: true,
    attributes: [
      { label: "Infantry March Speed", value: "+2%", color: "red" },
      { label: "Troop Defense", value: "+8%", color: "green" },
    ],
    materials: [
      { materialId: "leather", amount: 20 },
      { materialId: "iron", amount: 20 },
      { materialId: "ebony", amount: 20 },
    ],
    goldCost: 20000000,
  },
  {
    id: "witchs_hexed_cloak",
    name: "Witch's Hexed Cloak",
    slot: "chest",
    rarity: "legendary",
    equipmentLevel: 50,
    iconUrl: "/images/equipment/witchs_hexed_cloak.webp",
    canForge: true,
    attributes: [
      { label: "Siege Defense", value: "+4%", color: "purple" },
      { label: "Siege March Speed", value: "+2%", color: "purple" },
    ],
    specialTalent: "Gathering Speed 12%",
    materials: [
      { materialId: "bone", amount: 25 },
    ],
    goldCost: 20000000,
  },
  {
    id: "robe_of_the_forest_guardian",
    name: "Robe of the Forest Guardian",
    slot: "chest",
    rarity: "epic",
    equipmentLevel: 40,
    iconUrl: "/images/equipment/robe_of_the_forest_guardian.webp",
    canForge: true,
    attributes: [
      { label: "Archer Attack", value: "+4%", color: "pink" },
      { label: "Siege Attack", value: "+4%", color: "purple" },
    ],
    specialTalent: "Gathering Speed 8%",
    materials: [
      { materialId: "bone", amount: 25 },
    ],
    goldCost: 6000000,
  },
  {
    id: "quinns_soul",
    name: "Quinn's Soul",
    slot: "chest",
    rarity: "epic",
    equipmentLevel: 40,
    iconUrl: "/images/equipment/quinns_soul.webp",
    canForge: true,
    attributes: [
      { label: "Infantry Attack", value: "+8%", color: "red" },
      { label: "Archer Health", value: "+4%", color: "pink" },
    ],
    specialTalent: "Damage to Barbarians 5%",
    materials: [
      { materialId: "iron", amount: 40 },
      { materialId: "ebony", amount: 20 },
    ],
    goldCost: 5000000,
  },
  {
    id: "dark_lords_blessing",
    name: "Dark Lord's Blessing",
    slot: "chest",
    rarity: "epic",
    equipmentLevel: 40,
    iconUrl: "/images/equipment/dark_lords_blessing.webp",
    canForge: true,
    attributes: [
      { label: "Cavalry Defense", value: "+8%", color: "orange" },
      { label: "Archer Attack", value: "+5%", color: "pink" },
    ],
    materials: [
      { materialId: "leather", amount: 40 },
      { materialId: "ebony", amount: 20 },
    ],
    goldCost: 5000000,
  },
  {
    id: "revival_plate",
    name: "Revival Plate",
    slot: "chest",
    rarity: "epic",
    equipmentLevel: 40,
    iconUrl: "/images/equipment/revival_plate.webp",
    canForge: true,
    attributes: [
      { label: "Cavalry Defense", value: "+5%", color: "orange" },
      { label: "Archer Attack", value: "+7.5%", color: "pink" },
    ],
    materials: [
      { materialId: "leather", amount: 20 },
      { materialId: "ebony", amount: 40 },
    ],
    goldCost: 6000000,
  },
  {
    id: "knights_valorous_cloak",
    name: "Knight's Valorous Cloak",
    slot: "chest",
    rarity: "epic",
    equipmentLevel: 40,
    iconUrl: "/images/equipment/knights_valorous_cloak.webp",
    canForge: true,
    attributes: [
      { label: "Siege Attack", value: "+8%", color: "purple" },
      { label: "Siege March Speed", value: "+2%", color: "purple" },
    ],
    materials: [
      { materialId: "leather", amount: 20 },
      { materialId: "iron", amount: 20 },
      { materialId: "ebony", amount: 20 },
    ],
    goldCost: 5000000,
  },
  {
    id: "commanders_heavy_armor",
    name: "Commander's Heavy Armor",
    slot: "chest",
    rarity: "rare",
    equipmentLevel: 30,
    iconUrl: "/images/equipment/commanders_heavy_armor.webp",
    canForge: false,
    attributes: [
      { label: "Infantry Attack", value: "+3%", color: "red" },
      { label: "Archer Health", value: "+6%", color: "pink" },
    ],
    specialTalent: "Commander EXP Gain 3%",
    materials: [
      { materialId: "iron", amount: 20 },
      { materialId: "ebony", amount: 40 },
    ],
    goldCost: 2000000,
  },
  {
    id: "windswept_breastplate",
    name: "Windswept Breastplate",
    slot: "chest",
    rarity: "rare",
    equipmentLevel: 30,
    iconUrl: "/images/equipment/windswept_breastplate.webp",
    canForge: false,
    attributes: [
      { label: "Cavalry Defense", value: "+4.5%", color: "orange" },
      { label: "Infantry Defense", value: "+4.5%", color: "red" },
      { label: "Troop March Speed", value: "+3%", color: "green" },
    ],
    materials: [
      { materialId: "leather", amount: 30 },
      { materialId: "iron", amount: 30 },
    ],
    goldCost: 3000000,
  },
  {
    id: "harvester_robes",
    name: "Harvester Robes",
    slot: "chest",
    rarity: "rare",
    equipmentLevel: 30,
    iconUrl: "/images/equipment/harvester_robes.webp",
    canForge: false,
    attributes: [
      { label: "Siege Defense", value: "+3%", color: "purple" },
      { label: "Siege Health", value: "+3%", color: "purple" },
    ],
    specialTalent: "Gathering Speed 5%",
    materials: [
      { materialId: "bone", amount: 30 },
    ],
    goldCost: 3000000,
  },
  {
    id: "infantry_breastplate",
    name: "Infantry Breastplate",
    slot: "chest",
    rarity: "uncommon",
    equipmentLevel: 20,
    iconUrl: "/images/equipment/infantry_breastplate.webp",
    canForge: false,
    attributes: [
      { label: "Cavalry Health", value: "+2%", color: "orange" },
      { label: "Infantry Defense", value: "+4%", color: "red" },
    ],
    specialTalent: "Damage To Barbarians 3%",
    materials: [
      { materialId: "leather", amount: 10 },
      { materialId: "ebony", amount: 40 },
    ],
    goldCost: 500000,
  },
  {
    id: "milanese_plate",
    name: "Milanese Plate",
    slot: "chest",
    rarity: "uncommon",
    equipmentLevel: 20,
    iconUrl: "/images/equipment/milanese_plate.webp",
    canForge: false,
    attributes: [
      { label: "Cavalry Defense", value: "+4%", color: "orange" },
      { label: "Archer Attack", value: "+2%", color: "pink" },
    ],
    materials: [
      { materialId: "leather", amount: 40 },
      { materialId: "bone", amount: 10 },
    ],
    goldCost: 500000,
  },
  {
    id: "chain_mail",
    name: "Chain Mail",
    slot: "chest",
    rarity: "common",
    equipmentLevel: 10,
    iconUrl: "/images/equipment/chain_mail.webp",
    canForge: false,
    attributes: [
      { label: "Archer Attack", value: "+3%", color: "pink" },
    ],
    materials: [
      { materialId: "ebony", amount: 80 },
    ],
    goldCost: 100000,
  },
  {
    id: "vambraces_of_the_eternal_empire",
    name: "Vambraces of the Eternal Empire",
    slot: "gloves",
    rarity: "legendary",
    equipmentLevel: 50,
    iconUrl: "/images/equipment/vambraces_of_the_eternal_empire.webp",
    canForge: true,
    attributes: [
      { label: "Cavalry Attack", value: "+3%", color: "orange" },
      { label: "Infantry Defense", value: "+7.5%", color: "red" },
    ],
    materials: [
      { materialId: "leather", amount: 10 },
      { materialId: "iron", amount: 30 },
    ],
    goldCost: 20000000,
  },
  {
    id: "sacred_grips",
    name: "Sacred Grips",
    slot: "gloves",
    rarity: "legendary",
    equipmentLevel: 50,
    iconUrl: "/images/equipment/sacred_grips.webp",
    canForge: true,
    attributes: [
      { label: "Infantry Defense", value: "+8%", color: "red" },
      { label: "Archer Attack", value: "+5%", color: "pink" },
    ],
    materials: [
      { materialId: "iron", amount: 30 },
      { materialId: "ebony", amount: 10 },
    ],
    goldCost: 15000000,
  },
  {
    id: "ians_choice",
    name: "Ian's Choice",
    slot: "gloves",
    rarity: "legendary",
    equipmentLevel: 50,
    iconUrl: "/images/equipment/ians_choice.webp",
    canForge: true,
    attributes: [
      { label: "Archer Attack", value: "+8%", color: "pink" },
    ],
    specialTalent: "Commander EXP Gain 5%",
    materials: [
      { materialId: "leather", amount: 10 },
      { materialId: "ebony", amount: 30 },
    ],
    goldCost: 15000000,
  },
  {
    id: "navars_control",
    name: "Navar's Control",
    slot: "gloves",
    rarity: "legendary",
    equipmentLevel: 50,
    iconUrl: "/images/equipment/navars_control.webp",
    canForge: true,
    attributes: [
      { label: "Cavalry Health", value: "+8%", color: "orange" },
      { label: "Infantry Defense", value: "+5%", color: "red" },
    ],
    materials: [
      { materialId: "leather", amount: 30 },
      { materialId: "iron", amount: 10 },
    ],
    goldCost: 15000000,
  },
  {
    id: "dragons_breath_vambraces",
    name: "Dragon's Breath Vambraces",
    slot: "gloves",
    rarity: "legendary",
    equipmentLevel: 50,
    iconUrl: "/images/equipment/dragons_breath_vambraces.webp",
    canForge: true,
    attributes: [
      { label: "Infantry Attack", value: "+3%", color: "red" },
      { label: "Archer Attack", value: "+7.5%", color: "pink" },
    ],
    materials: [
      { materialId: "iron", amount: 10 },
      { materialId: "ebony", amount: 30 },
    ],
    goldCost: 20000000,
  },
  {
    id: "armband_of_the_hellish_wasteland",
    name: "Armband of the Hellish Wasteland",
    slot: "gloves",
    rarity: "legendary",
    equipmentLevel: 50,
    iconUrl: "/images/equipment/armband_of_the_hellish_wasteland.webp",
    canForge: true,
    attributes: [
      { label: "Cavalry Defense", value: "+7.5%", color: "orange" },
      { label: "Archer Health", value: "+3%", color: "pink" },
    ],
    materials: [
      { materialId: "leather", amount: 30 },
      { materialId: "ebony", amount: 10 },
    ],
    goldCost: 20000000,
  },
  {
    id: "wailing_wolfs_gauntlets",
    name: "Wailing Wolf's Gauntlets",
    slot: "gloves",
    rarity: "legendary",
    equipmentLevel: 50,
    iconUrl: "/images/equipment/wailing_wolfs_gauntlets.webp",
    canForge: true,
    attributes: [
      { label: "Siege Defense", value: "+10%", color: "purple" },
      { label: "Siege March Speed", value: "+3%", color: "purple" },
    ],
    materials: [
      { materialId: "leather", amount: 10 },
      { materialId: "iron", amount: 15 },
      { materialId: "ebony", amount: 15 },
    ],
    goldCost: 30000000,
  },
  {
    id: "gauntlets_of_the_glorious_goddess",
    name: "Gauntlets of the Glorious Goddess",
    slot: "gloves",
    rarity: "legendary",
    equipmentLevel: 50,
    iconUrl: "/images/equipment/gauntlets_of_the_glorious_goddess.webp",
    canForge: true,
    attributes: [
      { label: "Siege March Speed", value: "+2%", color: "purple" },
      { label: "Troop Defense", value: "+6%", color: "green" },
    ],
    materials: [
      { materialId: "leather", amount: 15 },
      { materialId: "iron", amount: 15 },
      { materialId: "ebony", amount: 10 },
    ],
    goldCost: 20000000,
  },
  {
    id: "witchs_crimson_bracers",
    name: "Witch's Crimson Bracers",
    slot: "gloves",
    rarity: "legendary",
    equipmentLevel: 50,
    iconUrl: "/images/equipment/witchs_crimson_bracers.webp",
    canForge: true,
    attributes: [
      { label: "Siege Health", value: "+3%", color: "purple" },
      { label: "Siege March Speed", value: "+2%", color: "purple" },
    ],
    specialTalent: "Gathering Speed 8%",
    materials: [
      { materialId: "bone", amount: 15 },
    ],
    goldCost: 20000000,
  },
  {
    id: "isets_sufferance",
    name: "Iset's Sufferance",
    slot: "gloves",
    rarity: "epic",
    equipmentLevel: 40,
    iconUrl: "/images/equipment/isets_sufferance.webp",
    canForge: true,
    attributes: [
      { label: "Cavalry Attack", value: "+3%", color: "orange" },
      { label: "Cavalry Health", value: "+3%", color: "orange" },
    ],
    materials: [
      { materialId: "leather", amount: 40 },
    ],
    goldCost: 5000000,
  },
  {
    id: "claws_of_the_forest_guardian",
    name: "Claws of the Forest Guardian",
    slot: "gloves",
    rarity: "epic",
    equipmentLevel: 40,
    iconUrl: "/images/equipment/claws_of_the_forest_guardian.webp",
    canForge: true,
    attributes: [
      { label: "Siege Attack", value: "+2%", color: "purple" },
      { label: "Siege Defense", value: "+2%", color: "purple" },
    ],
    specialTalent: "Gathering Speed 6%",
    materials: [
      { materialId: "bone", amount: 15 },
    ],
    goldCost: 6000000,
  },
  {
    id: "seths_brutality",
    name: "Seth's Brutality",
    slot: "gloves",
    rarity: "epic",
    equipmentLevel: 40,
    iconUrl: "/images/equipment/seths_brutality.webp",
    canForge: true,
    attributes: [
      { label: "Infantry Defense", value: "+5.5%", color: "red" },
      { label: "Archer Defense", value: "+2%", color: "pink" },
    ],
    specialTalent: "Damage to Barbarians 5%",
    materials: [
      { materialId: "iron", amount: 30 },
      { materialId: "ebony", amount: 10 },
    ],
    goldCost: 5000000,
  },
  {
    id: "revival_gauntlets",
    name: "Revival Gauntlets",
    slot: "gloves",
    rarity: "epic",
    equipmentLevel: 40,
    iconUrl: "/images/equipment/revival_gauntlets.webp",
    canForge: true,
    attributes: [
      { label: "Cavalry Attack", value: "+3%", color: "orange" },
      { label: "Infantry Attack", value: "+3%", color: "red" },
      { label: "Archer Attack", value: "+4.5%", color: "pink" },
    ],
    materials: [
      { materialId: "iron", amount: 10 },
      { materialId: "ebony", amount: 30 },
    ],
    goldCost: 6000000,
  },
  {
    id: "knights_battleworn_gauntlets",
    name: "Knight's Battleworn Gauntlets",
    slot: "gloves",
    rarity: "epic",
    equipmentLevel: 40,
    iconUrl: "/images/equipment/knights_battleworn_gauntlets.webp",
    canForge: true,
    attributes: [
      { label: "Siege Defense", value: "+5.5%", color: "purple" },
      { label: "Siege March Speed", value: "+2%", color: "purple" },
    ],
    materials: [
      { materialId: "leather", amount: 10 },
      { materialId: "iron", amount: 15 },
      { materialId: "ebony", amount: 15 },
    ],
    goldCost: 5000000,
  },
  {
    id: "saints_song",
    name: "Saint's Song",
    slot: "gloves",
    rarity: "rare",
    equipmentLevel: 30,
    iconUrl: "/images/equipment/saints_song.webp",
    canForge: false,
    attributes: [
      { label: "Cavalry Attack", value: "+2%", color: "orange" },
      { label: "Archer Attack", value: "+4%", color: "pink" },
    ],
    specialTalent: "Commander EXP Gain 3%",
    materials: [
      { materialId: "leather", amount: 10 },
      { materialId: "ebony", amount: 30 },
    ],
    goldCost: 2000000,
  },
  {
    id: "windswept_bracers",
    name: "Windswept Bracers",
    slot: "gloves",
    rarity: "rare",
    equipmentLevel: 30,
    iconUrl: "/images/equipment/windswept_bracers.webp",
    canForge: false,
    attributes: [
      { label: "Cavalry Health", value: "+2.5%", color: "orange" },
      { label: "Infantry Health", value: "+2.5%", color: "red" },
      { label: "Troop March Speed", value: "+3%", color: "green" },
    ],
    materials: [
      { materialId: "leather", amount: 20 },
      { materialId: "iron", amount: 20 },
    ],
    goldCost: 3000000,
  },
  {
    id: "calvins_hand",
    name: "Calvin's Hand",
    slot: "gloves",
    rarity: "rare",
    equipmentLevel: 30,
    iconUrl: "/images/equipment/calvins_hand.webp",
    canForge: false,
    attributes: [
      { label: "Infantry Attack", value: "+4%", color: "red" },
      { label: "Infantry Health", value: "+1%", color: "red" },
      { label: "Archer Attack", value: "+1%", color: "pink" },
    ],
    materials: [
      { materialId: "leather", amount: 5 },
      { materialId: "iron", amount: 30 },
      { materialId: "ebony", amount: 5 },
    ],
    goldCost: 2000000,
  },
  {
    id: "leather_gloves",
    name: "Leather Gloves",
    slot: "gloves",
    rarity: "uncommon",
    equipmentLevel: 20,
    iconUrl: "/images/equipment/leather_gloves.webp",
    canForge: false,
    attributes: [
      { label: "Infantry Defense", value: "+1%", color: "red" },
      { label: "Archer Health", value: "+2.5%", color: "pink" },
    ],
    materials: [
      { materialId: "leather", amount: 15 },
      { materialId: "iron", amount: 20 },
    ],
    goldCost: 500000,
  },
  {
    id: "bronze_bracers",
    name: "Bronze Bracers",
    slot: "gloves",
    rarity: "uncommon",
    equipmentLevel: 20,
    iconUrl: "/images/equipment/bronze_bracers.webp",
    canForge: false,
    attributes: [
      { label: "Cavalry Defense", value: "+2.5%", color: "orange" },
      { label: "Infantry Health", value: "+1%", color: "red" },
    ],
    specialTalent: "Damage to Barbarians 3%",
    materials: [
      { materialId: "leather", amount: 20 },
      { materialId: "iron", amount: 15 },
    ],
    goldCost: 500000,
  },
  {
    id: "cloth_gloves",
    name: "Cloth Gloves",
    slot: "gloves",
    rarity: "common",
    equipmentLevel: 10,
    iconUrl: "/images/equipment/cloth_gloves.webp",
    canForge: false,
    attributes: [
      { label: "Infantry Defense", value: "+2%", color: "red" },
    ],
    materials: [
      { materialId: "leather", amount: 60 },
    ],
    goldCost: 100000,
  },
  {
    id: "ash_of_the_dawn",
    name: "Ash of the Dawn",
    slot: "legs",
    rarity: "legendary",
    equipmentLevel: 50,
    iconUrl: "/images/equipment/ash_of_the_dawn.webp",
    canForge: true,
    attributes: [
      { label: "Cavalry Health", value: "+12%", color: "orange" },
      { label: "Infantry Health", value: "+5%", color: "red" },
    ],
    specialTalent: "Commander EXP Gain 5%",
    materials: [
      { materialId: "leather", amount: 40 },
      { materialId: "iron", amount: 10 },
      { materialId: "ebony", amount: 10 },
    ],
    goldCost: 15000000,
  },
  {
    id: "greaves_of_the_eternal_empire",
    name: "Greaves of the Eternal Empire",
    slot: "legs",
    rarity: "legendary",
    equipmentLevel: 50,
    iconUrl: "/images/equipment/greaves_of_the_eternal_empire.webp",
    canForge: true,
    attributes: [
      { label: "Infantry Attack", value: "+11%", color: "red" },
      { label: "Archer Defense", value: "+5%", color: "pink" },
    ],
    materials: [
      { materialId: "leather", amount: 10 },
      { materialId: "iron", amount: 40 },
      { materialId: "ebony", amount: 10 },
    ],
    goldCost: 20000000,
  },
  {
    id: "tassets_of_the_war_god",
    name: "Tassets of the War God",
    slot: "legs",
    rarity: "legendary",
    equipmentLevel: 50,
    iconUrl: "/images/equipment/tassets_of_the_war_god.webp",
    canForge: true,
    attributes: [
      { label: "Cavalry Attack", value: "+5%", color: "orange" },
      { label: "Infantry Attack", value: "+5%", color: "red" },
      { label: "Archer Attack", value: "+12%", color: "pink" },
    ],
    materials: [
      { materialId: "leather", amount: 10 },
      { materialId: "iron", amount: 10 },
      { materialId: "ebony", amount: 40 },
    ],
    goldCost: 15000000,
  },
  {
    id: "eternal_night",
    name: "Eternal Night",
    slot: "legs",
    rarity: "legendary",
    equipmentLevel: 50,
    iconUrl: "/images/equipment/eternal_night.webp",
    canForge: true,
    attributes: [
      { label: "Cavalry Defense", value: "+5%", color: "orange" },
      { label: "Infantry Defense", value: "+12%", color: "red" },
      { label: "Archer Defense", value: "+5%", color: "pink" },
    ],
    materials: [
      { materialId: "leather", amount: 10 },
      { materialId: "iron", amount: 40 },
      { materialId: "ebony", amount: 10 },
    ],
    goldCost: 15000000,
  },
  {
    id: "dragons_breath_tassets",
    name: "Dragon's Breath Tassets",
    slot: "legs",
    rarity: "legendary",
    equipmentLevel: 50,
    iconUrl: "/images/equipment/dragons_breath_tassets.webp",
    canForge: true,
    attributes: [
      { label: "Cavalry Attack", value: "+5%", color: "orange" },
      { label: "Archer Attack", value: "+11%", color: "pink" },
    ],
    materials: [
      { materialId: "leather", amount: 10 },
      { materialId: "iron", amount: 10 },
      { materialId: "ebony", amount: 40 },
    ],
    goldCost: 20000000,
  },
  {
    id: "tassets_of_the_hellish_wasteland",
    name: "Tassets of the Hellish Wasteland",
    slot: "legs",
    rarity: "legendary",
    equipmentLevel: 50,
    iconUrl: "/images/equipment/tassets_of_the_hellish_wasteland.webp",
    canForge: true,
    attributes: [
      { label: "Cavalry Attack", value: "+11%", color: "orange" },
      { label: "Infantry Defense", value: "+5%", color: "red" },
    ],
    materials: [
      { materialId: "leather", amount: 40 },
      { materialId: "iron", amount: 10 },
      { materialId: "ebony", amount: 10 },
    ],
    goldCost: 20000000,
  },
  {
    id: "lone_wolfs_leather_tassets",
    name: "Lone Wolf's Leather Tassets",
    slot: "legs",
    rarity: "legendary",
    equipmentLevel: 50,
    iconUrl: "/images/equipment/lone_wolfs_leather_tassets.webp",
    canForge: true,
    attributes: [
      { label: "Siege Health", value: "+14.5%", color: "purple" },
      { label: "Siege March Speed", value: "+4%", color: "purple" },
    ],
    materials: [
      { materialId: "leather", amount: 20 },
      { materialId: "iron", amount: 20 },
      { materialId: "ebony", amount: 20 },
    ],
    goldCost: 30000000,
  },
  {
    id: "chausses_of_the_glorious_goddess",
    name: "Chausses of the Glorious Goddess",
    slot: "legs",
    rarity: "legendary",
    equipmentLevel: 50,
    iconUrl: "/images/equipment/chausses_of_the_glorious_goddess.webp",
    canForge: true,
    attributes: [
      { label: "Archer March Speed", value: "+2%", color: "pink" },
      { label: "Troop Health", value: "+8%", color: "green" },
    ],
    materials: [
      { materialId: "leather", amount: 20 },
      { materialId: "iron", amount: 20 },
      { materialId: "ebony", amount: 20 },
    ],
    goldCost: 20000000,
  },
  {
    id: "witchs_ornamented_pants",
    name: "Witch's Ornamented Pants",
    slot: "legs",
    rarity: "legendary",
    equipmentLevel: 50,
    iconUrl: "/images/equipment/witchs_ornamented_pants.webp",
    canForge: true,
    attributes: [
      { label: "Siege Health", value: "+4%", color: "purple" },
      { label: "Siege March Speed", value: "+2%", color: "purple" },
    ],
    specialTalent: "Gathering Speed 12%",
    materials: [
      { materialId: "bone", amount: 25 },
    ],
    goldCost: 20000000,
  },
  {
    id: "fanatics_tassets",
    name: "Fanatic's Tassets",
    slot: "legs",
    rarity: "epic",
    equipmentLevel: 40,
    iconUrl: "/images/equipment/fanatics_tassets.webp",
    canForge: true,
    attributes: [
      { label: "Cavalry Defense", value: "+5%", color: "orange" },
      { label: "Archer Defense", value: "+8%", color: "pink" },
    ],
    materials: [
      { materialId: "leather", amount: 20 },
      { materialId: "ebony", amount: 40 },
    ],
    goldCost: 5000000,
  },
  {
    id: "gladiator",
    name: "Gladiator",
    slot: "legs",
    rarity: "epic",
    equipmentLevel: 40,
    iconUrl: "/images/equipment/gladiator.webp",
    canForge: true,
    attributes: [
      { label: "Cavalry Health", value: "+8%", color: "orange" },
      { label: "Archer Defense", value: "+4%", color: "pink" },
    ],
    specialTalent: "Damage to Barbarians 5%",
    materials: [
      { materialId: "leather", amount: 40 },
      { materialId: "ebony", amount: 20 },
    ],
    goldCost: 5000000,
  },
  {
    id: "karuaks_humility",
    name: "Karuak's Humility",
    slot: "legs",
    rarity: "epic",
    equipmentLevel: 40,
    iconUrl: "/images/equipment/karuaks_humility.webp",
    canForge: true,
    attributes: [
      { label: "Cavalry Attack", value: "+5%", color: "orange" },
      { label: "Infantry Health", value: "+8%", color: "red" },
    ],
    materials: [
      { materialId: "leather", amount: 20 },
      { materialId: "iron", amount: 40 },
    ],
    goldCost: 5000000,
  },
  {
    id: "revival_greaves",
    name: "Revival Greaves",
    slot: "legs",
    rarity: "epic",
    equipmentLevel: 40,
    iconUrl: "/images/equipment/revival_greaves.webp",
    canForge: true,
    attributes: [
      { label: "Cavalry Attack", value: "+5%", color: "orange" },
      { label: "Archer Defense", value: "+7.5%", color: "pink" },
    ],
    materials: [
      { materialId: "leather", amount: 20 },
      { materialId: "ebony", amount: 40 },
    ],
    goldCost: 6000000,
  },
  {
    id: "knights_triumphant_tassets",
    name: "Knight's Triumphant Tassets",
    slot: "legs",
    rarity: "epic",
    equipmentLevel: 40,
    iconUrl: "/images/equipment/knights_triumphant_tassets.webp",
    canForge: true,
    attributes: [
      { label: "Siege Defense", value: "+8%", color: "purple" },
    ],
    specialTalent: "Damage to Barbarians 5%",
    materials: [
      { materialId: "leather", amount: 20 },
      { materialId: "iron", amount: 20 },
      { materialId: "ebony", amount: 20 },
    ],
    goldCost: 5000000,
  },
  {
    id: "harvester_breeches",
    name: "Harvester Breeches",
    slot: "legs",
    rarity: "rare",
    equipmentLevel: 30,
    iconUrl: "/images/equipment/harvester_breeches.webp",
    canForge: false,
    attributes: [
      { label: "Siege Attack", value: "+3%", color: "purple" },
      { label: "Siege Defense", value: "+3%", color: "purple" },
    ],
    specialTalent: "Gathering Speed 5%",
    materials: [
      { materialId: "bone", amount: 30 },
    ],
    goldCost: 3000000,
  },
  {
    id: "greaves_of_the_exile",
    name: "Greaves of the Exile",
    slot: "legs",
    rarity: "rare",
    equipmentLevel: 30,
    iconUrl: "/images/equipment/greaves_of_the_exile.webp",
    canForge: false,
    attributes: [
      { label: "Infantry Defense", value: "+3%", color: "red" },
      { label: "Archer Defense", value: "+6%", color: "pink" },
    ],
    specialTalent: "Commander EXP Gain 3%",
    materials: [
      { materialId: "iron", amount: 20 },
      { materialId: "ebony", amount: 40 },
    ],
    goldCost: 2000000,
  },
  {
    id: "sentry_breeches",
    name: "Sentry Breeches",
    slot: "legs",
    rarity: "rare",
    equipmentLevel: 30,
    iconUrl: "/images/equipment/sentry_breeches.webp",
    canForge: false,
    attributes: [
      { label: "Cavalry Defense", value: "+1%", color: "orange" },
      { label: "Infantry Attack", value: "+6%", color: "red" },
      { label: "Archer Attack", value: "+3%", color: "pink" },
    ],
    materials: [
      { materialId: "leather", amount: 10 },
      { materialId: "iron", amount: 40 },
      { materialId: "ebony", amount: 10 },
    ],
    goldCost: 2000000,
  },
  {
    id: "vanguard_greaves",
    name: "Vanguard Greaves",
    slot: "legs",
    rarity: "uncommon",
    equipmentLevel: 20,
    iconUrl: "/images/equipment/vanguard_greaves.webp",
    canForge: false,
    attributes: [
      { label: "Cavalry Attack", value: "+4%", color: "orange" },
      { label: "Cavalry Health", value: "+1%", color: "orange" },
    ],
    materials: [
      { materialId: "leather", amount: 70 },
    ],
    goldCost: 750000,
  },
  {
    id: "ranger_trousers",
    name: "Ranger Trousers",
    slot: "legs",
    rarity: "uncommon",
    equipmentLevel: 20,
    iconUrl: "/images/equipment/ranger_trousers.webp",
    canForge: false,
    attributes: [
      { label: "Infantry Attack", value: "+4%", color: "red" },
      { label: "Archer Defense", value: "+2%", color: "pink" },
    ],
    specialTalent: "Damage to Barbarians 3%",
    materials: [
      { materialId: "iron", amount: 40 },
      { materialId: "ebony", amount: 10 },
    ],
    goldCost: 500000,
  },
  {
    id: "coarse_breeches",
    name: "Coarse Breeches",
    slot: "legs",
    rarity: "common",
    equipmentLevel: 10,
    iconUrl: "/images/equipment/coarse_breeches.webp",
    canForge: false,
    attributes: [
      { label: "Cavalry Attack", value: "+3%", color: "orange" },
    ],
    specialTalent: "Gathering Speed 1%",
    materials: [
      { materialId: "ebony", amount: 60 },
    ],
    goldCost: 100000,
  },
  {
    id: "shios_return",
    name: "Shio's Return",
    slot: "boots",
    rarity: "legendary",
    equipmentLevel: 50,
    iconUrl: "/images/equipment/shios_return.webp",
    canForge: true,
    attributes: [
      { label: "Infantry Defense", value: "+8%", color: "red" },
      { label: "Archer Health", value: "+5%", color: "pink" },
    ],
    materials: [
      { materialId: "iron", amount: 30 },
      { materialId: "ebony", amount: 10 },
    ],
    goldCost: 15000000,
  },
  {
    id: "commanders_boots",
    name: "Commander's Boots",
    slot: "boots",
    rarity: "legendary",
    equipmentLevel: 50,
    iconUrl: "/images/equipment/commanders_boots.webp",
    canForge: true,
    attributes: [
      { label: "Archer Attack", value: "+8%", color: "pink" },
    ],
    specialTalent: "Commander EXP Gain 5%",
    materials: [
      { materialId: "leather", amount: 10 },
      { materialId: "ebony", amount: 30 },
    ],
    goldCost: 15000000,
  },
  {
    id: "sturdy_boots_of_the_eternal_empire",
    name: "Sturdy Boots of the Eternal Empire",
    slot: "boots",
    rarity: "legendary",
    equipmentLevel: 50,
    iconUrl: "/images/equipment/sturdy_boots_of_the_eternal_empire.webp",
    canForge: true,
    attributes: [
      { label: "Cavalry Defense", value: "+3%", color: "orange" },
      { label: "Infantry Defense", value: "+7.5%", color: "red" },
    ],
    materials: [
      { materialId: "leather", amount: 10 },
      { materialId: "iron", amount: 30 },
    ],
    goldCost: 20000000,
  },
  {
    id: "mountain_crushers",
    name: "Mountain Crushers",
    slot: "boots",
    rarity: "legendary",
    equipmentLevel: 50,
    iconUrl: "/images/equipment/mountain_crushers.webp",
    canForge: true,
    attributes: [
      { label: "Cavalry Attack", value: "+8%", color: "orange" },
      { label: "Archer Attack", value: "+5%", color: "pink" },
    ],
    materials: [
      { materialId: "leather", amount: 30 },
      { materialId: "ebony", amount: 10 },
    ],
    goldCost: 15000000,
  },
  {
    id: "boots_of_the_hellish_wasteland",
    name: "Boots of the Hellish Wasteland",
    slot: "boots",
    rarity: "legendary",
    equipmentLevel: 50,
    iconUrl: "/images/equipment/boots_of_the_hellish_wasteland.webp",
    canForge: true,
    attributes: [
      { label: "Cavalry Health", value: "+7.5%", color: "orange" },
      { label: "Archer Attack", value: "+3%", color: "pink" },
    ],
    materials: [
      { materialId: "leather", amount: 30 },
      { materialId: "ebony", amount: 10 },
    ],
    goldCost: 20000000,
  },
  {
    id: "dragons_breath_boots",
    name: "Dragon's Breath Boots",
    slot: "boots",
    rarity: "legendary",
    equipmentLevel: 50,
    iconUrl: "/images/equipment/dragons_breath_boots.webp",
    canForge: true,
    attributes: [
      { label: "Infantry Defense", value: "+3%", color: "red" },
      { label: "Archer Defense", value: "+7.5%", color: "pink" },
    ],
    materials: [
      { materialId: "iron", amount: 10 },
      { materialId: "ebony", amount: 30 },
    ],
    goldCost: 20000000,
  },
  {
    id: "roaring_wolfs_claws",
    name: "Roaring Wolf's Claws",
    slot: "boots",
    rarity: "legendary",
    equipmentLevel: 50,
    iconUrl: "/images/equipment/roaring_wolfs_claws.webp",
    canForge: true,
    attributes: [
      { label: "Siege Defense", value: "+10%", color: "purple" },
      { label: "Siege March Speed", value: "+3%", color: "purple" },
    ],
    materials: [
      { materialId: "leather", amount: 15 },
      { materialId: "iron", amount: 10 },
      { materialId: "ebony", amount: 15 },
    ],
    goldCost: 30000000,
  },
  {
    id: "greaves_of_the_glorious_goddess",
    name: "Greaves of the Glorious Goddess",
    slot: "boots",
    rarity: "legendary",
    equipmentLevel: 50,
    iconUrl: "/images/equipment/greaves_of_the_glorious_goddess.webp",
    canForge: true,
    attributes: [
      { label: "Siege March Speed", value: "+2%", color: "purple" },
      { label: "Troop Health", value: "+7%", color: "green" },
    ],
    materials: [
      { materialId: "leather", amount: 10 },
      { materialId: "iron", amount: 15 },
      { materialId: "ebony", amount: 15 },
    ],
    goldCost: 20000000,
  },
  {
    id: "witchs_mire_waders",
    name: "Witch's Mire-Waders",
    slot: "boots",
    rarity: "legendary",
    equipmentLevel: 50,
    iconUrl: "/images/equipment/witchs_mire_waders.webp",
    canForge: true,
    attributes: [
      { label: "Siege Attack", value: "+3%", color: "purple" },
      { label: "Siege March Speed", value: "+2%", color: "purple" },
    ],
    specialTalent: "Gathering Speed 8%",
    materials: [
      { materialId: "bone", amount: 15 },
    ],
    goldCost: 20000000,
  },
  {
    id: "cloud_racers",
    name: "Cloud Racers",
    slot: "boots",
    rarity: "epic",
    equipmentLevel: 40,
    iconUrl: "/images/equipment/cloud_racers.webp",
    canForge: true,
    attributes: [
      { label: "Cavalry Attack", value: "+5.5%", color: "orange" },
      { label: "Archer Health", value: "+2%", color: "pink" },
    ],
    specialTalent: "Gathering Speed 6%",
    materials: [
      { materialId: "leather", amount: 30 },
      { materialId: "ebony", amount: 10 },
    ],
    goldCost: 5000000,
  },
  {
    id: "flame_treads",
    name: "Flame Treads",
    slot: "boots",
    rarity: "epic",
    equipmentLevel: 40,
    iconUrl: "/images/equipment/flame_treads.webp",
    canForge: true,
    attributes: [
      { label: "Cavalry Attack", value: "+3%", color: "orange" },
      { label: "Archer Health", value: "+5.5%", color: "pink" },
    ],
    materials: [
      { materialId: "leather", amount: 10 },
      { materialId: "ebony", amount: 30 },
    ],
    goldCost: 5000000,
  },
  {
    id: "frost_treads",
    name: "Frost Treads",
    slot: "boots",
    rarity: "epic",
    equipmentLevel: 40,
    iconUrl: "/images/equipment/frost_treads.webp",
    canForge: true,
    attributes: [
      { label: "Infantry Defense", value: "+5.5%", color: "red" },
    ],
    specialTalent: "Damage to Barbarians 5%",
    materials: [
      { materialId: "leather", amount: 10 },
      { materialId: "iron", amount: 30 },
    ],
    goldCost: 5000000,
  },
  {
    id: "knights_winter_sabatons",
    name: "Knight's Winter Sabatons",
    slot: "boots",
    rarity: "epic",
    equipmentLevel: 40,
    iconUrl: "/images/equipment/knights_winter_sabatons.webp",
    canForge: true,
    attributes: [
      { label: "Siege Health", value: "+5.5%", color: "purple" },
    ],
    specialTalent: "Damage to Barbarians 5%",
    materials: [
      { materialId: "leather", amount: 15 },
      { materialId: "iron", amount: 10 },
      { materialId: "ebony", amount: 15 },
    ],
    goldCost: 5000000,
  },
  {
    id: "harvester_boots",
    name: "Harvester Boots",
    slot: "boots",
    rarity: "rare",
    equipmentLevel: 30,
    iconUrl: "/images/equipment/harvester_boots.webp",
    canForge: false,
    attributes: [
      { label: "Siege Defense", value: "+2%", color: "purple" },
      { label: "Siege Health", value: "+2%", color: "purple" },
    ],
    specialTalent: "Gathering Speed 5%",
    materials: [
      { materialId: "bone", amount: 20 },
    ],
    goldCost: 3000000,
  },
  {
    id: "the_scarlet_hounds",
    name: "The Scarlet Hounds",
    slot: "boots",
    rarity: "rare",
    equipmentLevel: 30,
    iconUrl: "/images/equipment/the_scarlet_hounds.webp",
    canForge: false,
    attributes: [
      { label: "Infantry Health", value: "+4%", color: "red" },
    ],
    specialTalent: "Commander EXP Gain 3%",
    materials: [
      { materialId: "iron", amount: 40 },
    ],
    goldCost: 2000000,
  },
  {
    id: "windswept_boots",
    name: "Windswept Boots",
    slot: "boots",
    rarity: "rare",
    equipmentLevel: 30,
    iconUrl: "/images/equipment/windswept_boots.webp",
    canForge: false,
    attributes: [
      { label: "Cavalry Health", value: "+2.5%", color: "orange" },
      { label: "Infantry Defense", value: "+2.5%", color: "red" },
      { label: "Troop March Speed", value: "+3%", color: "green" },
    ],
    materials: [
      { materialId: "leather", amount: 20 },
      { materialId: "iron", amount: 20 },
    ],
    goldCost: 3000000,
  },
  {
    id: "edged_boots",
    name: "Edged Boots",
    slot: "boots",
    rarity: "uncommon",
    equipmentLevel: 20,
    iconUrl: "/images/equipment/edged_boots.webp",
    canForge: false,
    attributes: [
      { label: "Cavalry Attack", value: "+1%", color: "orange" },
      { label: "Archer Attack", value: "+2.5%", color: "pink" },
    ],
    specialTalent: "Damage to Barbarians 3%",
    materials: [
      { materialId: "leather", amount: 15 },
      { materialId: "ebony", amount: 20 },
    ],
    goldCost: 500000,
  },
  {
    id: "boots_of_reverence",
    name: "Boots of Reverence",
    slot: "boots",
    rarity: "uncommon",
    equipmentLevel: 20,
    iconUrl: "/images/equipment/boots_of_reverence.webp",
    canForge: false,
    attributes: [
      { label: "Infantry Attack", value: "+2%", color: "red" },
      { label: "Archer Defense", value: "+1%", color: "pink" },
    ],
    materials: [
      { materialId: "leather", amount: 20 },
      { materialId: "iron", amount: 15 },
    ],
    goldCost: 500000,
  },
  {
    id: "sturdy_boots",
    name: "Sturdy Boots",
    slot: "boots",
    rarity: "common",
    equipmentLevel: 10,
    iconUrl: "/images/equipment/sturdy_boots.webp",
    canForge: false,
    attributes: [
      { label: "Archer Defense", value: "+2%", color: "pink" },
    ],
    specialTalent: "Gathering Speed 1%",
    materials: [
      { materialId: "ebony", amount: 60 },
    ],
    goldCost: 100000,
  },
  {
    id: "scolas_lucky_coin",
    name: "Scola's Lucky Coin",
    slot: "accessory",
    rarity: "legendary",
    equipmentLevel: 50,
    iconUrl: "/images/equipment/scolas_lucky_coin.webp",
    canForge: true,
    attributes: [],
    specialTalent: "10% Chance to gain Shield",
    materials: [
      { materialId: "leather", amount: 40 },
      { materialId: "iron", amount: 40 },
      { materialId: "ebony", amount: 40 },
    ],
    goldCost: 50000000,
  },
  {
    id: "karuaks_war_drums",
    name: "Karuak's War Drums",
    slot: "accessory",
    rarity: "legendary",
    equipmentLevel: 50,
    iconUrl: "/images/equipment/karuaks_war_drums.webp",
    canForge: true,
    attributes: [],
    specialTalent: "10% Chance to grant 50 Extra Rage for itself & up to 2 allies.",
    materials: [
      { materialId: "leather", amount: 30 },
      { materialId: "iron", amount: 40 },
      { materialId: "ebony", amount: 30 },
    ],
    goldCost: 50000000,
  },
  {
    id: "pendant_of_eternal_night",
    name: "Pendant of Eternal Night",
    slot: "accessory",
    rarity: "legendary",
    equipmentLevel: 50,
    iconUrl: "/images/equipment/pendant_of_eternal_night.webp",
    canForge: true,
    attributes: [],
    specialTalent: "Skill Damage 5%",
    materials: [
      { materialId: "leather", amount: 40 },
      { materialId: "iron", amount: 40 },
      { materialId: "ebony", amount: 40 },
    ],
    goldCost: 5000000,
  },
  {
    id: "ring_of_doom",
    name: "Ring of Doom",
    slot: "accessory",
    rarity: "legendary",
    equipmentLevel: 50,
    iconUrl: "/images/equipment/ring_of_doom.webp",
    canForge: true,
    attributes: [],
    specialTalent: "10% Chance to gain 50% Bonus Damage",
    materials: [
      { materialId: "leather", amount: 40 },
      { materialId: "iron", amount: 40 },
      { materialId: "ebony", amount: 40 },
    ],
    goldCost: 5000000,
  },
  {
    id: "greatest_glory",
    name: "Greatest Glory",
    slot: "accessory",
    rarity: "legendary",
    equipmentLevel: 50,
    iconUrl: "/images/equipment/greatest_glory.webp",
    canForge: true,
    attributes: [],
    specialTalent: "Normal Damage 5%",
    materials: [
      { materialId: "leather", amount: 40 },
      { materialId: "iron", amount: 40 },
      { materialId: "ebony", amount: 40 },
    ],
    goldCost: 50000000,
  },
  {
    id: "horn_of_fury",
    name: "Horn of Fury",
    slot: "accessory",
    rarity: "legendary",
    equipmentLevel: 50,
    iconUrl: "/images/equipment/horn_of_fury.webp",
    canForge: true,
    attributes: [],
    specialTalent: "30% Chance to gain 50 Extra Rage",
    materials: [
      { materialId: "leather", amount: 40 },
      { materialId: "iron", amount: 40 },
      { materialId: "ebony", amount: 40 },
    ],
    goldCost: 5000000,
  },
  {
    id: "concealed_dagger",
    name: "Concealed Dagger",
    slot: "accessory",
    rarity: "legendary",
    equipmentLevel: 50,
    iconUrl: "/images/equipment/concealed_dagger.webp",
    canForge: true,
    attributes: [],
    specialTalent: "30% Chance to reduce target Health 5%",
    materials: [
      { materialId: "leather", amount: 40 },
      { materialId: "iron", amount: 40 },
      { materialId: "ebony", amount: 40 },
    ],
    goldCost: 50000000,
  },
  {
    id: "moras_web",
    name: "Mora's Web",
    slot: "accessory",
    rarity: "legendary",
    equipmentLevel: 50,
    iconUrl: "/images/equipment/moras_web.webp",
    canForge: true,
    attributes: [],
    specialTalent: "30% Chance to reduce target Defence 4%",
    materials: [
      { materialId: "leather", amount: 40 },
      { materialId: "iron", amount: 40 },
      { materialId: "ebony", amount: 40 },
    ],
    goldCost: 50000000,
  },
  {
    id: "vengeance",
    name: "Vengeance",
    slot: "accessory",
    rarity: "legendary",
    equipmentLevel: 50,
    iconUrl: "/images/equipment/vengeance.webp",
    canForge: true,
    attributes: [],
    specialTalent: "Counterattack Damage 8%",
    materials: [
      { materialId: "leather", amount: 40 },
      { materialId: "iron", amount: 40 },
      { materialId: "ebony", amount: 40 },
    ],
    goldCost: 50000000,
  },
  {
    id: "seths_call",
    name: "Seth's Call",
    slot: "accessory",
    rarity: "legendary",
    equipmentLevel: 50,
    iconUrl: "/images/equipment/seths_call.webp",
    canForge: true,
    attributes: [],
    specialTalent: "10% Chance to grant 10% Attack Bonus",
    materials: [
      { materialId: "leather", amount: 30 },
      { materialId: "iron", amount: 30 },
      { materialId: "ebony", amount: 40 },
    ],
    goldCost: 50000000,
  },
  {
    id: "immolating_plume",
    name: "Immolating Plume",
    slot: "accessory",
    rarity: "legendary",
    equipmentLevel: 50,
    iconUrl: "/images/equipment/immolating_plume.webp",
    canForge: true,
    attributes: [],
    specialTalent: "50% Chance to increase 30% Damage",
    materials: [
      { materialId: "leather", amount: 40 },
      { materialId: "iron", amount: 40 },
      { materialId: "ebony", amount: 40 },
    ],
    goldCost: 50000000,
  },
  {
    id: "heros_hilt",
    name: "Hero's Hilt",
    slot: "accessory",
    rarity: "legendary",
    equipmentLevel: 50,
    iconUrl: "/images/equipment/heros_hilt.webp",
    canForge: true,
    attributes: [],
    specialTalent: "50% Chance 3% Combo Attack",
    materials: [
      { materialId: "leather", amount: 40 },
      { materialId: "iron", amount: 40 },
      { materialId: "ebony", amount: 40 },
    ],
    goldCost: 50000000,
  },
  {
    id: "saddle_of_a_thousand_blessings",
    name: "Saddle of a Thousand Blessings",
    slot: "accessory",
    rarity: "legendary",
    equipmentLevel: 50,
    iconUrl: "/images/equipment/saddle_of_a_thousand_blessings.webp",
    canForge: true,
    attributes: [],
    specialTalent: "Smite Damage 3%",
    materials: [
      { materialId: "leather", amount: 40 },
      { materialId: "iron", amount: 40 },
      { materialId: "ebony", amount: 40 },
    ],
    goldCost: 50000000,
  },
  {
    id: "peters_sickle",
    name: "Peter's Sickle",
    slot: "accessory",
    rarity: "epic",
    equipmentLevel: 40,
    iconUrl: "/images/equipment/peters_sickle.webp",
    canForge: true,
    attributes: [],
    specialTalent: "Gathering Speed 10%",
    materials: [
      { materialId: "bone", amount: 80 },
    ],
    goldCost: 8000000,
  },
  {
    id: "wind_scars",
    name: "Wind Scars",
    slot: "accessory",
    rarity: "epic",
    equipmentLevel: 40,
    iconUrl: "/images/equipment/wind_scars.webp",
    canForge: true,
    attributes: [
      { label: "Infantry March Speed", value: "+8%", color: "red" },
    ],
    materials: [
      { materialId: "leather", amount: 30 },
      { materialId: "iron", amount: 20 },
      { materialId: "ebony", amount: 20 },
    ],
    goldCost: 8000000,
  },
  {
    id: "delanes_amulet",
    name: "Delane's Amulet",
    slot: "accessory",
    rarity: "epic",
    equipmentLevel: 40,
    iconUrl: "/images/equipment/delanes_amulet.webp",
    canForge: true,
    attributes: [],
    specialTalent: "Less Counterattack Damage 5%",
    materials: [
      { materialId: "leather", amount: 30 },
      { materialId: "iron", amount: 20 },
      { materialId: "ebony", amount: 20 },
    ],
    goldCost: 8000000,
  },
  {
    id: "silent_trial",
    name: "Silent Trial",
    slot: "accessory",
    rarity: "epic",
    equipmentLevel: 40,
    iconUrl: "/images/equipment/silent_trial.webp",
    canForge: true,
    attributes: [],
    specialTalent: "Basic Attack, target loses 10 Rage",
    materials: [
      { materialId: "leather", amount: 20 },
      { materialId: "iron", amount: 20 },
      { materialId: "ebony", amount: 30 },
    ],
    goldCost: 8000000,
  },
  {
    id: "the_bards_pendant",
    name: "The Bard's Pendant",
    slot: "accessory",
    rarity: "epic",
    equipmentLevel: 40,
    iconUrl: "/images/equipment/the_bards_pendant.webp",
    canForge: true,
    attributes: [],
    specialTalent: "Extra RSS from Gathering 5%",
    materials: [
      { materialId: "bone", amount: 80 },
    ],
    goldCost: 8000000,
  },
  {
    id: "crimson_ring",
    name: "Crimson Ring",
    slot: "accessory",
    rarity: "epic",
    equipmentLevel: 40,
    iconUrl: "/images/equipment/crimson_ring.webp",
    canForge: true,
    attributes: [],
    specialTalent: "Commander EXP Gain 15%",
    materials: [
      { materialId: "bone", amount: 80 },
    ],
    goldCost: 8000000,
  },
  {
    id: "ancient_stratagems",
    name: "Ancient Stratagems",
    slot: "accessory",
    rarity: "epic",
    equipmentLevel: 40,
    iconUrl: "/images/equipment/ancient_stratagems.webp",
    canForge: true,
    attributes: [],
    specialTalent: "Unit Capacity 3%",
    materials: [
      { materialId: "leather", amount: 20 },
      { materialId: "iron", amount: 20 },
      { materialId: "ebony", amount: 30 },
    ],
    goldCost: 8000000,
  },
  {
    id: "savage_totem",
    name: "Savage Totem",
    slot: "accessory",
    rarity: "rare",
    equipmentLevel: 30,
    iconUrl: "/images/equipment/savage_totem.webp",
    canForge: false,
    attributes: [],
    specialTalent: "Damage to Barbarians 10%",
    materials: [
      { materialId: "bone", amount: 70 },
    ],
    goldCost: 4000000,
  },
  {
    id: "lohars_bone_necklace",
    name: "Lohar's Bone Necklace",
    slot: "accessory",
    rarity: "rare",
    equipmentLevel: 30,
    iconUrl: "/images/equipment/lohars_bone_necklace.webp",
    canForge: false,
    attributes: [],
    specialTalent: "Commander EXP Gain 10%",
    materials: [
      { materialId: "bone", amount: 70 },
    ],
    goldCost: 4000000,
  },
  {
    id: "call_of_the_loyal",
    name: "Call of the Loyal",
    slot: "accessory",
    rarity: "rare",
    equipmentLevel: 30,
    iconUrl: "/images/equipment/call_of_the_loyal.webp",
    canForge: false,
    attributes: [
      { label: "Troop March Speed", value: "+5%", color: "green" },
    ],
    materials: [
      { materialId: "leather", amount: 35 },
      { materialId: "iron", amount: 35 },
    ],
    goldCost: 4000000,
  },
]
